server:
  port: 9557

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #      eureka-service端的url
      #            defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: gateway9557 #隐藏主机名
    prefer-ip-address: true #访问路径显示ip地址
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/**

        - id: payment_route2
          uri: http://localhost:8001
          predicates:
              - Path=/feign-timeout