server:
  port: 8006

spring:
  application:
    name: cloud-hystrix-payment-service
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true #开启hystrix的断路器（circuitbreaker）

eureka:
  client:
    register-with-eureka: true #是否向注册中心注册自己
    fetchRegistry: true #是否从注册中心抓取已有的注册信息 默认true，集群必须设置为true
    service-url:
      #      eureka-service端的url
      #            defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: hystrix-payment8006  #隐藏主机名
    prefer-ip-address: true #访问路径显示ip地址